format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$fill\
$memory_usage\
$conda\
$python\
$line_break\
$character"""

add_newline = true

palette = "catppuccin_mocha"

[directory]
style = 'bold fg:green'
repo_root_style = 'bold fg:blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '.../'
truncate_to_repo = false
repo_root_format = '[ $repo_root]( $repo_root_style)[$path ]($repo_root_style)'

[git_branch]
style = 'bold fg:text'
symbol = ' '
format = '[$symbol$branch ]($style)'

[git_status]
style = 'bold fg:red'
modified = 'M'
deleted = 'D'
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 500
style = 'fg:overlay2'
format = '[$duration]($style)'
show_notifications = true

[fill]
symbol = ' '

[memory_usage]
disabled = false
threshold = -1
style = 'bold text'
symbol = '💾'
format = '$symbol[${ram_pct}]($style) '


[conda]
style = 'blue'
symbol = ' '
format = '[$environment $symbol]($style)'

[python]
style = 'blue'
symbol = ' '
version_format = '${major}.${minor}'
format = '[($virtualenv )${symbol}${pyenv_prefix}(${version} )]($style)'
pyenv_version_name = false
pyenv_prefix = ''
detect_files = []
detect_extensions = []

[line_break]
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
